src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 * @UniqueEntity("email")
 * @Vich\Uploadable()
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */

    private $filename;

     /**

     * @var File|null
     * @Vich\UploadableField(mapping="review_image", fileNameProperty="filename")
     */
   private $imageFile;


    /**
     * @Assert\Regex ("/^[^\W][a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\@[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\.[a-zA-Z]{2,4}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=1, max=5)
     */
    private $note;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    // public function getFilename() {
	// 	return $this->filename;
	// }

	// public function setFilename(?string $filename) {
    //     $this->$filename = $filename;
    //     return $this;
	// }

    // public function getImageFile() {
	// 	return $this->imageFile;
	// }

	// public function setImageFile(?File $imageFile) {
    //     $this->imageFile = $imageFile;
    //     if ($this->imageFile instanceof UploadedFile) {
    //         $this->created_at = new \DateTime('now');
    //     }
    //     return $this;
    // }
    
    /**
    * Get the value of imageFile
    *
    * @return  File
    */ 
   public function getImageFile()
   {
      return $this->imageFile;
   }

   /**
    * Set the value of imageFile
    *
    * @param  File  $imageFile
    *
    * @return  self
    */ 
   public function setImageFile($imageFile)
   {
      $this->imageFile = $imageFile;
      if ($this->imageFile instanceof UploadedFile) {
        $this->updated_At = new \DateTime('now');
    }
      return $this;
   }

    /**
     * Get the value of filename
     */ 
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set the value of filename
     *
     * @return  self
     */ 
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        
        {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="/assets/css/style.css">
        <meta name="viewport" content="width=device-width, user-scalable=no">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div id="articleBackground"></div>

    <div class="container">
        <div class="row">
            <div class="row">
                <img src="https://cdn.fizzup.com/full/landing_01/images/logowhite_v2.png" id="logo" alt="">
            </div>
        </div>
    
        <div class="row">
             <img class="col-lg-6 col-md-12 img-fluid" src='https://www.fizzup.com/wp-content/uploads/2015/05/programme-abdominaux-exercice-musculation.jpg' height="300px" align="left" />
        <h2 class="col-lg-6 col-md-12 text-center" id="title">COMMENT MUSCLER SES ABDOMINAUX ?</h2>
        </div>
        <p class="slogan">« Vous voulez que vos bras soient plus gros et vos pectoraux plus dessinés ? »</p>

    <p>
        Quelle est la solution pour augmenter la <b>masse de ces groupes musculaires</b> ? L’<b>entrainement</b>, la <b>surcharge progressive</b> (augmentation de la difficulté au fil du temps), l’<b>assiduité</b> et un <b>surplus calorique</b>.

        Contrairement aux idées reçues, vos <b>abdominaux</b> sont un groupe musculaire qui requiert la même formule et la même attention. Mais pour une raison quelconque, beaucoup considèrent les abdominaux comme une partie du corps <i>« spéciale »</i> qui nécessite des règles <b>d’entrainement</b> complètement différentes.

        Pour muscler ses <b>abdominaux</b>, vous devez les entrainer en <b>musculation</b> avec <b>intensité</b> et la <b>surcharge progressive</b>. Pour cela vous devez <b>suivre un programme précis</b> et ne pas vous laisser aller au hasard.

        Chaque séance doit être bien agencée en ce qui concerne les <b>exercices</b>, les <b>séries</b>, les <b>répétitions</b> et les <b>temps de repos</b> afin de vous faire progresser sur la durée. Si vous souhaitez muscler vos abdominaux, il est important de bien prendre en compte cette notion de programmation. <b>FizzUp</b> vous propose divers <b>programmes</b> et <b>séances d’entrainement des abdominaux afin de les muscler adéquatement</b>.
    </p>

    <div class="card" id="form">
        <div class="card-header">
            Cette article vous à plus ? Laissez nous un avis !
        </div>
        <div class="card-body">
            <h5 class="card-title">Écrire un avis</h5>
            <p class="card-text">
                {{ form_start(form) }}
                    <div class="row">
                        <div class="col-md-6 col-sm-12">{{ form_row(form.email) }}</div>
                        <div class="col-md-6 col-sm-12">{{ form_row(form.pseudo) }}</div>
                        <div class="col-md-6 col-sm-12">{{ form_row(form.note) }}</div>
                        <div class="col-md-6 col-sm-12">{{ form_row(form.imageFile) }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">{{ form_row(form.commentaire) }}</div>
                        
                    </div>

                    <button class="btn btn-primary">Ajouter</button>
                {{ form_end(form) }}
            </p>
        </div>
    </div>
    


 
        <div class="row">
            <div class="col-md-4">
                <div class="card bg-light" style="max-width: 18rem;">
                    <div class="card-header">Trier par:</div>
                    <div class="card-body">
                    <p class="card-text">
                        {{ form_start(formSearch) }}
                        <div class="form-row">
                            <div class="col-12">
                                {{ form_row(formSearch.reviewMax )}}
                            </div>
                            <div class="col-12">
                                {{ form_row(formSearch.reviewSort )}}
                            </div>
                            <div class="col-12">
                                {{ form_row(formSearch.date )}}
                            </div>
                        </div>
                        
                        <button class="btn btn-primary">Rechercher</button>
                        {{ form_end(formSearch) }} 
                    </p>
                    </div>
                </div>
            </div>
            
            <div class="col-md-8">

                <div class="card bg-light mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Avis</h5>
                        <p class="card-text">
                            {% for review in reviews %}
                                <div class="card mb-3" style="max-width: 540px;">
                                    <div class="row no-gutters">
                                        <div class="col-md-4">
                                        {% if review.filename is not empty %}
                                        <img src="/images/review/{{ review.filename }}" class="card-img" alt="...">
                                        {% else %}
                                        <img src="/images/review/anon.png" class="card-img" alt="...">
                                        {% endif %}
        
                                        </div>
                                        <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ review.pseudo }}</h5>
                                            {% for i in 1..review.note %}
                                                <i class="fas fa-star"></i>
                                            {% endfor %}
                                            <p class="card-text">{{ review.commentaire| raw }}</p>
                                            <p class="card-text"><small class="text-muted">le {{ review.createdAt|date("d/m/Y") }}</small></p>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            
                            {% if reviews is empty and GET is empty %}
                                <i>Aucun avis à été laisser pour le moment, laissez le votre!</i>
                            {% endif %}
        
                            {% if reviews is empty and GET is not empty %}
                                <i>Aucun résultat pour cette recherche</i>
                            {% endif %}

                        </p>
                    </div>
                </div>
            </div>   
    </div>

{% endblock %}